2016/05/04 03:24:35 [error] [exception.CException] exception 'CException' with message 'Alias "boostrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('boostrap.compon...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('boostrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:25:33 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:25:35 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:31:21 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:32:58 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:32:59 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:33:00 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:38:06 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:38:06 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:38:07 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:38:07 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:38:08 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:39:50 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:39:51 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:39:52 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:39:52 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:41:11 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:41:31 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Bootstrap" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:44:56 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.widgets.TbBox" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\web\CWidgetFactory.php(146): YiiBase::import('bootstrap.widge...', true)
#1 C:\wamp64\www\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'bootstrap.widge...', Array)
#2 C:\wamp64\www\framework\web\CBaseController.php(197): CBaseController->createWidget('bootstrap.widge...', Array)
#3 C:\wamp64\www\psushi2\protected\extensions\heart\views\layouts\column1.php(14): CBaseController->beginWidget('bootstrap.widge...', Array)
#4 C:\wamp64\www\framework\web\CBaseController.php(126): require('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\wamp64\\www\\p...', Array, true)
#6 C:\wamp64\www\framework\web\CController.php(784): CBaseController->renderFile('C:\\wamp64\\www\\p...', Array, true)
#7 C:\wamp64\www\psushi2\protected\controllers\SiteController.php(32): CController->render('index')
#8 C:\wamp64\www\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#9 C:\wamp64\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\wamp64\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\wamp64\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\wamp64\www\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:44:58 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.widgets.TbBox" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\web\CWidgetFactory.php(146): YiiBase::import('bootstrap.widge...', true)
#1 C:\wamp64\www\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'bootstrap.widge...', Array)
#2 C:\wamp64\www\framework\web\CBaseController.php(197): CBaseController->createWidget('bootstrap.widge...', Array)
#3 C:\wamp64\www\psushi2\protected\extensions\heart\views\layouts\column1.php(14): CBaseController->beginWidget('bootstrap.widge...', Array)
#4 C:\wamp64\www\framework\web\CBaseController.php(126): require('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\wamp64\\www\\p...', Array, true)
#6 C:\wamp64\www\framework\web\CController.php(784): CBaseController->renderFile('C:\\wamp64\\www\\p...', Array, true)
#7 C:\wamp64\www\psushi2\protected\controllers\SiteController.php(32): CController->render('index')
#8 C:\wamp64\www\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#9 C:\wamp64\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\wamp64\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\wamp64\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\wamp64\www\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:49:22 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:49:23 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:49:38 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:50:29 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:51:08 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:51:09 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:51:10 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:51:10 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:51:11 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.components.Booster" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\YiiBase.php(196): YiiBase::import('bootstrap.compo...', true)
#1 C:\wamp64\www\framework\base\CModule.php(393): YiiBase::createComponent(Array)
#2 C:\wamp64\www\framework\base\CModule.php(530): CModule->getComponent('bootstrap')
#3 C:\wamp64\www\framework\base\CApplication.php(168): CModule->preloadComponents()
#4 C:\wamp64\www\framework\YiiBase.php(125): CApplication->__construct('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\YiiBase.php(98): YiiBase::createApplication('CWebApplication', 'C:\\wamp64\\www\\p...')
#6 C:\wamp64\www\psushi2\index.php(13): YiiBase::createWebApplication('C:\\wamp64\\www\\p...')
#7 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:51:47 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.widgets.TbBox" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\web\CWidgetFactory.php(146): YiiBase::import('bootstrap.widge...', true)
#1 C:\wamp64\www\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'bootstrap.widge...', Array)
#2 C:\wamp64\www\framework\web\CBaseController.php(197): CBaseController->createWidget('bootstrap.widge...', Array)
#3 C:\wamp64\www\psushi2\protected\extensions\heart\views\layouts\column1.php(14): CBaseController->beginWidget('bootstrap.widge...', Array)
#4 C:\wamp64\www\framework\web\CBaseController.php(126): require('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\wamp64\\www\\p...', Array, true)
#6 C:\wamp64\www\framework\web\CController.php(784): CBaseController->renderFile('C:\\wamp64\\www\\p...', Array, true)
#7 C:\wamp64\www\psushi2\protected\controllers\SiteController.php(32): CController->render('index')
#8 C:\wamp64\www\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#9 C:\wamp64\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\wamp64\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\wamp64\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\wamp64\www\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 03:51:58 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.widgets.TbBox" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\wamp64\www\framework\YiiBase.php:323
Stack trace:
#0 C:\wamp64\www\framework\web\CWidgetFactory.php(146): YiiBase::import('bootstrap.widge...', true)
#1 C:\wamp64\www\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'bootstrap.widge...', Array)
#2 C:\wamp64\www\framework\web\CBaseController.php(197): CBaseController->createWidget('bootstrap.widge...', Array)
#3 C:\wamp64\www\psushi2\protected\extensions\heart\views\layouts\column1.php(14): CBaseController->beginWidget('bootstrap.widge...', Array)
#4 C:\wamp64\www\framework\web\CBaseController.php(126): require('C:\\wamp64\\www\\p...')
#5 C:\wamp64\www\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\wamp64\\www\\p...', Array, true)
#6 C:\wamp64\www\framework\web\CController.php(784): CBaseController->renderFile('C:\\wamp64\\www\\p...', Array, true)
#7 C:\wamp64\www\psushi2\protected\controllers\SiteController.php(32): CController->render('index')
#8 C:\wamp64\www\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#9 C:\wamp64\www\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\wamp64\www\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\wamp64\www\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\wamp64\www\framework\web\CWebApplication.php(282): CController->run('')
#13 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/psushi2/
---
2016/05/04 04:44:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/heart".' in C:\wamp64\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/heart')
#1 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/psushi2/index.php?r=gii/heart
HTTP_REFERER=http://localhost/psushi2/index.php
---
2016/05/04 04:45:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii/heart".' in C:\wamp64\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/heart')
#1 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/psushi2/index.php?r=gii/heart
---
2016/05/04 07:04:47 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:04:53 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:05:02 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:05:04 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:05:11 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:05:14 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:05:48 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:05:50 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\wamp64\www\psushi2\index.php (13)
2016/05/04 07:56:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "?r=administrador/index".' in C:\wamp64\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('?r=administrado...')
#1 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/psushi2/index.php?r=?r=administrador/index
HTTP_REFERER=http://localhost/psushi2/
---
2016/05/04 07:57:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "?r=administrador/index".' in C:\wamp64\www\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\wamp64\www\framework\web\CWebApplication.php(141): CWebApplication->runController('?r=administrado...')
#1 C:\wamp64\www\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\wamp64\www\psushi2\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/psushi2/index.php?r=?r=administrador/index
---
2016/05/10 17:09:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\yii\Psushi\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi/index.php?r=gii/default/index
---
2016/05/12 03:20:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2386): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Administrador))
#7 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Yii\psushi2\protected\controllers\AdministradorController.php(228): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): AdministradorController->actionIndex()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('administrador/i...')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=administrador/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php
---
2016/05/12 03:20:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(637): CApplication->getDb()
#5 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(2386): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Administrador))
#7 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\xampp\htdocs\Yii\psushi2\protected\controllers\AdministradorController.php(228): CActiveRecord->__construct('search')
#9 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): AdministradorController->actionIndex()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#19 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('administrador/i...')
#20 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=administrador/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php
---
2016/05/12 03:23:02 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\psushi2\protected\extensions\heart\gii\crud\CrudCode.php(53): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): CrudCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:49 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:37:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:38:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 17:38:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'grupo314userdb'@'localhost' (using password: YES)' in C:\xampp\htdocs\Yii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\Yii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\Yii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\Yii\framework\base\CModule.php(103): CModule->getComponent('db')
#4 C:\xampp\htdocs\Yii\framework\gii\generators\model\ModelCode.php(60): CModule->__get('db')
#5 C:\xampp\htdocs\Yii\framework\web\CFormModel.php(39): ModelCode->init()
#6 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(153): CFormModel->__construct()
#7 C:\xampp\htdocs\Yii\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('index')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Yii\psushi2\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/yii/Psushi2/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/yii/Psushi2/index.php?r=gii/default/index
---
2016/05/18 18:09:25 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\xampp\htdocs\Yii\psushi2\index.php (13)
2016/05/18 18:09:34 [warning] [application] Failed to set unsafe attribute "file" of "CrudCode".
in C:\xampp\htdocs\Yii\psushi2\index.php (13)
